"""Generate frontend/src/strings.js from the Android app's Strings.kt.

The web app and the APK must show exactly the same text. Re-run after editing Strings.kt:
    python frontend/scripts/sync_strings.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "android/app/src/main/java/com/gramtext/app/Strings.kt"
OUT = ROOT / "frontend/src/strings.js"

src = SRC.read_text(encoding="utf-8")


def block(name: str) -> dict:
    body = re.search(name + r" = Strings\((.*?)\n\)", src, re.S).group(1)
    return {key: json.loads(value) for key, value in re.findall(r'(\w+) = ("(?:[^"\\]|\\.)*")', body)}


hi, en = block("val HindiStrings"), block("val EnglishStrings")
assert hi.keys() == en.keys(), set(hi) ^ set(en)

# Web-only: browsers need one tap before they may play sound.
hi.update(startReading="पढ़ना शुरू करें", startHint="फिर बस लेबल को बॉक्स में दिखाएँ")
en.update(startReading="Start reading", startHint="Then just show labels inside the box")

OUT.write_text(
    "// GENERATED by frontend/scripts/sync_strings.py from android/.../Strings.kt,\n"
    "// so the web app and the APK show identical text. Do not edit by hand.\n"
    "// Only startReading/startHint are web-only (browsers need one tap before playing sound).\n"
    f"export const HINDI = {json.dumps(hi, ensure_ascii=False, indent=2)};\n\n"
    f"export const ENGLISH = {json.dumps(en, ensure_ascii=False, indent=2)};\n",
    encoding="utf-8",
)
print(f"{len(hi)} strings -> {OUT}")
