package com.gramtext.app

import androidx.compose.runtime.staticCompositionLocalOf

/** In-app UI language. Hindi is the default for the target users. */
enum class AppLanguage { HINDI, ENGLISH }

data class Strings(
    val appTagline: String,
    val takePhoto: String,
    val takePhotoHint: String,
    val pickGallery: String,
    val pickGalleryHint: String,
    val settings: String,
    val back: String,
    val serverOnline: String,
    val serverOffline: String,
    val serverChecking: String,
    val capture: String,
    val cameraPermission: String,
    val grantPermission: String,
    val reading: String,
    val detectedText: String,
    val editHint: String,
    val readAloud: String,
    val preparingAudio: String,
    val stop: String,
    val scanAgain: String,
    val copy: String,
    val copied: String,
    val speed: String,
    val slow: String,
    val normal: String,
    val wasCorrect: String,
    val yes: String,
    val no: String,
    val sendCorrection: String,
    val sendCorrectionBody: String,
    val send: String,
    val dontSend: String,
    val thanks: String,
    val noText: String,
    val readBy: String,
    val engineModel: String,
    val engineGemini: String,
    val serverAddress: String,
    val testConnection: String,
    val autoRead: String,
    val autoReadHint: String,
    val language: String,
    val showEngine: String,
    val disclaimer: String,
    val networkError: String,
    val timeoutError: String,
    val imageError: String,
    val save: String,
    val saved: String,
    val liveOn: String,
    val liveOff: String,
    val liveHint: String,
    val liveReadingNow: String,
    val liveSetting: String,
    val liveSettingHint: String,
    val gallery: String,
    val boxHint: String,
    val spokeIn: String,
)

val HindiStrings = Strings(
    appTagline = "फ़ोटो खींचें — हम पढ़कर सुनाएँगे",
    takePhoto = "फ़ोटो खींचें",
    takePhotoHint = "दवा, पर्चा या सूचना की फ़ोटो",
    pickGallery = "गैलरी से चुनें",
    pickGalleryHint = "पहले से ली गई फ़ोटो",
    settings = "सेटिंग्स",
    back = "वापस",
    serverOnline = "सर्वर जुड़ा है",
    serverOffline = "सर्वर से संपर्क नहीं",
    serverChecking = "जाँच हो रही है…",
    capture = "फ़ोटो लें",
    cameraPermission = "फ़ोटो लेने के लिए कैमरे की अनुमति चाहिए।",
    grantPermission = "अनुमति दें",
    reading = "पढ़ रहे हैं…",
    detectedText = "पहचाना गया लेख",
    editHint = "गलती हो तो यहाँ ठीक करें",
    readAloud = "पढ़कर सुनाएँ",
    preparingAudio = "आवाज़ तैयार हो रही है…",
    stop = "रोकें",
    scanAgain = "नई फ़ोटो",
    copy = "कॉपी",
    copied = "कॉपी हो गया",
    speed = "गति",
    slow = "धीरे",
    normal = "सामान्य",
    wasCorrect = "क्या यह सही पढ़ा गया?",
    yes = "हाँ",
    no = "नहीं",
    sendCorrection = "सुधार भेजें?",
    sendCorrectionBody = "आपका ठीक किया हुआ लेख ऐप को बेहतर बनाने के लिए भेजा जाएगा। फ़ोटो नहीं भेजी जाएगी।",
    send = "भेजें",
    dontSend = "न भेजें",
    thanks = "धन्यवाद! आपकी राय दर्ज हो गई।",
    noText = "इस फ़ोटो में पढ़ने लायक लेख नहीं मिला। साफ़ और पास से फ़ोटो लें।",
    readBy = "पढ़ा गया",
    engineModel = "GramText मॉडल",
    engineGemini = "बैकअप AI",
    serverAddress = "सर्वर का पता",
    testConnection = "जाँचें",
    autoRead = "अपने-आप पढ़कर सुनाएँ",
    autoReadHint = "लेख मिलते ही आवाज़ चलेगी",
    language = "भाषा / Language",
    showEngine = "तकनीकी जानकारी दिखाएँ",
    disclaimer = "GramText केवल लिखा हुआ पढ़कर सुनाता है। दवा के बारे में सलाह के लिए डॉक्टर या फ़ार्मासिस्ट से पूछें।",
    networkError = "सर्वर से संपर्क नहीं हो पाया। इंटरनेट जाँचें और फिर कोशिश करें।",
    timeoutError = "बहुत समय लग गया। फिर कोशिश करें।",
    imageError = "यह फ़ोटो खुल नहीं पाई। दूसरी फ़ोटो चुनें।",
    save = "सहेजें",
    saved = "सहेज लिया",
    liveOn = "लाइव: चालू",
    liveOff = "लाइव: बंद",
    liveHint = "लेबल को फ़्रेम में स्थिर रखें — अपने-आप पढ़कर सुनाया जाएगा",
    liveReadingNow = "पढ़ रहे हैं…",
    liveSetting = "लाइव पढ़ना",
    liveSettingHint = "कैमरा खुलते ही हर नया लेबल अपने-आप पढ़ा जाएगा",
    gallery = "गैलरी",
    boxHint = "लेबल को बॉक्स के अंदर रखें — सिर्फ़ बॉक्स के अंदर का लेख पढ़ा जाएगा",
    spokeIn = "बोलना शुरू",
)

val EnglishStrings = Strings(
    appTagline = "Take a photo — we'll read it aloud",
    takePhoto = "Take photo",
    takePhotoHint = "Medicine, prescription or notice",
    pickGallery = "Choose from gallery",
    pickGalleryHint = "A photo you already took",
    settings = "Settings",
    back = "Back",
    serverOnline = "Server connected",
    serverOffline = "Cannot reach server",
    serverChecking = "Checking…",
    capture = "Capture",
    cameraPermission = "Camera permission is needed to take a photo.",
    grantPermission = "Allow",
    reading = "Reading…",
    detectedText = "Detected text",
    editHint = "Fix any mistakes here",
    readAloud = "Read aloud",
    preparingAudio = "Preparing audio…",
    stop = "Stop",
    scanAgain = "New photo",
    copy = "Copy",
    copied = "Copied",
    speed = "Speed",
    slow = "Slow",
    normal = "Normal",
    wasCorrect = "Was this read correctly?",
    yes = "Yes",
    no = "No",
    sendCorrection = "Send your correction?",
    sendCorrectionBody = "Your corrected text will be sent to help improve the app. The photo is not sent.",
    send = "Send",
    dontSend = "Don't send",
    thanks = "Thank you! Your feedback was recorded.",
    noText = "No readable text found. Take a clear, close-up photo.",
    readBy = "Read by",
    engineModel = "GramText model",
    engineGemini = "Backup AI",
    serverAddress = "Server address",
    testConnection = "Test",
    autoRead = "Read aloud automatically",
    autoReadHint = "Audio starts as soon as text is found",
    language = "भाषा / Language",
    showEngine = "Show technical details",
    disclaimer = "GramText only reads printed text aloud. For medicine advice, ask a doctor or pharmacist.",
    networkError = "Could not reach the server. Check the internet and try again.",
    timeoutError = "This took too long. Please try again.",
    imageError = "This photo could not be opened. Choose another one.",
    save = "Save",
    saved = "Saved",
    liveOn = "Live: on",
    liveOff = "Live: off",
    liveHint = "Hold a label steady in the frame — it is read aloud automatically",
    liveReadingNow = "Reading…",
    liveSetting = "Live reading",
    liveSettingHint = "Every new label in front of the camera is read aloud automatically",
    gallery = "Gallery",
    boxHint = "Keep the label inside the box — only text inside the box is read",
    spokeIn = "Started speaking in",
)

fun stringsFor(language: AppLanguage) = if (language == AppLanguage.HINDI) HindiStrings else EnglishStrings

val LocalStrings = staticCompositionLocalOf { HindiStrings }
